import { storage } from "./storage.js";

const bibleIn1YearPlan = [
  { day: 1, readings: ["GEN.1", "GEN.2"], title: "The Beginning" },
  { day: 2, readings: ["GEN.3", "GEN.4", "GEN.5"], title: "The Fall and Early Humanity" },
  { day: 3, readings: ["GEN.6", "GEN.7", "GEN.8", "GEN.9"], title: "Noah and the Flood" },
  { day: 4, readings: ["GEN.10", "GEN.11"], title: "Nations and Babel" },
  { day: 5, readings: ["GEN.12", "GEN.13", "GEN.14"], title: "Abraham's Call" },
  { day: 6, readings: ["GEN.15", "GEN.16", "GEN.17"], title: "God's Covenant with Abraham" },
  { day: 7, readings: ["GEN.18", "GEN.19"], title: "Sodom and Gomorrah" },
  { day: 8, readings: ["GEN.20", "GEN.21", "GEN.22"], title: "Isaac and the Test" },
  { day: 9, readings: ["GEN.23", "GEN.24"], title: "Finding a Wife for Isaac" },
  { day: 10, readings: ["GEN.25", "GEN.26"], title: "Jacob and Esau" },
  { day: 11, readings: ["GEN.27", "GEN.28"], title: "Jacob's Blessing and Journey" },
  { day: 12, readings: ["GEN.29", "GEN.30"], title: "Jacob's Wives and Children" },
  { day: 13, readings: ["GEN.31", "GEN.32"], title: "Jacob Returns" },
  { day: 14, readings: ["GEN.33", "GEN.34", "GEN.35"], title: "Reconciliation and Loss" },
  { day: 15, readings: ["GEN.36", "GEN.37"], title: "Joseph Sold into Slavery" },
  { day: 16, readings: ["GEN.38", "GEN.39", "GEN.40"], title: "Joseph in Egypt" },
  { day: 17, readings: ["GEN.41"], title: "Joseph Interprets Pharaoh's Dreams" },
  { day: 18, readings: ["GEN.42", "GEN.43"], title: "Brothers Come to Egypt" },
  { day: 19, readings: ["GEN.44", "GEN.45"], title: "Joseph Reveals Himself" },
  { day: 20, readings: ["GEN.46", "GEN.47"], title: "Jacob's Family in Egypt" },
  { day: 21, readings: ["GEN.48", "GEN.49", "GEN.50"], title: "Jacob's Blessing and Death" },
  { day: 22, readings: ["EXO.1", "EXO.2"], title: "Moses' Birth" },
  { day: 23, readings: ["EXO.3", "EXO.4"], title: "The Burning Bush" },
  { day: 24, readings: ["EXO.5", "EXO.6"], title: "Moses Confronts Pharaoh" },
  { day: 25, readings: ["EXO.7", "EXO.8"], title: "First Plagues" },
  { day: 26, readings: ["EXO.9", "EXO.10"], title: "More Plagues" },
  { day: 27, readings: ["EXO.11", "EXO.12"], title: "Passover and Exodus" },
  { day: 28, readings: ["EXO.13", "EXO.14"], title: "Red Sea Crossing" },
  { day: 29, readings: ["EXO.15", "EXO.16"], title: "Manna from Heaven" },
  { day: 30, readings: ["EXO.17", "EXO.18"], title: "Water from the Rock" },
  { day: 31, readings: ["EXO.19", "EXO.20"], title: "The Ten Commandments" },
  { day: 32, readings: ["EXO.21", "EXO.22"], title: "Laws for Living" },
  { day: 33, readings: ["EXO.23", "EXO.24"], title: "Covenant Confirmed" },
  { day: 34, readings: ["EXO.25", "EXO.26"], title: "Tabernacle Plans" },
  { day: 35, readings: ["EXO.27", "EXO.28"], title: "Altar and Priestly Garments" },
  { day: 36, readings: ["EXO.29", "EXO.30"], title: "Consecration of Priests" },
  { day: 37, readings: ["EXO.31", "EXO.32"], title: "The Golden Calf" },
  { day: 38, readings: ["EXO.33", "EXO.34"], title: "Moses Sees God's Glory" },
  { day: 39, readings: ["EXO.35", "EXO.36"], title: "Building the Tabernacle" },
  { day: 40, readings: ["EXO.37", "EXO.38", "EXO.39", "EXO.40"], title: "Tabernacle Completed" },
  { day: 41, readings: ["LEV.1", "LEV.2", "LEV.3"], title: "Offerings to God" },
  { day: 42, readings: ["LEV.4", "LEV.5", "LEV.6"], title: "Sin and Guilt Offerings" },
  { day: 43, readings: ["LEV.7", "LEV.8"], title: "Priestly Ordination" },
  { day: 44, readings: ["LEV.9", "LEV.10"], title: "Nadab and Abihu" },
  { day: 45, readings: ["LEV.11", "LEV.12"], title: "Clean and Unclean" },
  { day: 46, readings: ["LEV.13"], title: "Laws About Skin Diseases" },
  { day: 47, readings: ["LEV.14"], title: "Cleansing from Diseases" },
  { day: 48, readings: ["LEV.15", "LEV.16"], title: "Day of Atonement" },
  { day: 49, readings: ["LEV.17", "LEV.18"], title: "Unlawful Sexual Relations" },
  { day: 50, readings: ["LEV.19", "LEV.20"], title: "Be Holy" },
  { day: 51, readings: ["LEV.21", "LEV.22"], title: "Priestly Conduct" },
  { day: 52, readings: ["LEV.23", "LEV.24"], title: "Appointed Festivals" },
  { day: 53, readings: ["LEV.25"], title: "Sabbath Year and Jubilee" },
  { day: 54, readings: ["LEV.26", "LEV.27"], title: "Blessings and Curses" },
  { day: 55, readings: ["NUM.1", "NUM.2"], title: "Census of Israel" },
  { day: 56, readings: ["NUM.3", "NUM.4"], title: "Duties of the Levites" },
  { day: 57, readings: ["NUM.5", "NUM.6"], title: "Nazirite Vow" },
  { day: 58, readings: ["NUM.7"], title: "Offerings of the Leaders" },
  { day: 59, readings: ["NUM.8", "NUM.9"], title: "The Passover" },
  { day: 60, readings: ["NUM.10", "NUM.11"], title: "Journey from Sinai" },
  { day: 61, readings: ["NUM.12", "NUM.13"], title: "Spying Out Canaan" },
  { day: 62, readings: ["NUM.14"], title: "Rebellion and Judgment" },
  { day: 63, readings: ["NUM.15", "NUM.16"], title: "Korah's Rebellion" },
  { day: 64, readings: ["NUM.17", "NUM.18"], title: "Aaron's Staff Buds" },
  { day: 65, readings: ["NUM.19", "NUM.20"], title: "Water from the Rock" },
  { day: 66, readings: ["NUM.21"], title: "Bronze Serpent" },
  { day: 67, readings: ["NUM.22", "NUM.23"], title: "Balaam's Donkey" },
  { day: 68, readings: ["NUM.24", "NUM.25"], title: "Balaam's Oracles" },
  { day: 69, readings: ["NUM.26", "NUM.27"], title: "Second Census" },
  { day: 70, readings: ["NUM.28", "NUM.29"], title: "Offerings and Festivals" },
  { day: 71, readings: ["NUM.30", "NUM.31"], title: "War Against Midian" },
  { day: 72, readings: ["NUM.32", "NUM.33"], title: "Tribes East of Jordan" },
  { day: 73, readings: ["NUM.34", "NUM.35", "NUM.36"], title: "Boundaries of Canaan" },
  { day: 74, readings: ["DEU.1", "DEU.2"], title: "Moses Recalls the Journey" },
  { day: 75, readings: ["DEU.3", "DEU.4"], title: "Moses' Command to Obey" },
  { day: 76, readings: ["DEU.5", "DEU.6"], title: "The Shema" },
  { day: 77, readings: ["DEU.7", "DEU.8"], title: "Remember the Lord" },
  { day: 78, readings: ["DEU.9", "DEU.10"], title: "The Golden Calf Revisited" },
  { day: 79, readings: ["DEU.11", "DEU.12"], title: "Love and Obey" },
  { day: 80, readings: ["DEU.13", "DEU.14"], title: "Worship the Lord Alone" },
  { day: 81, readings: ["DEU.15", "DEU.16"], title: "Year of Release" },
  { day: 82, readings: ["DEU.17", "DEU.18"], title: "Laws for Kings and Prophets" },
  { day: 83, readings: ["DEU.19", "DEU.20"], title: "Cities of Refuge" },
  { day: 84, readings: ["DEU.21", "DEU.22"], title: "Various Laws" },
  { day: 85, readings: ["DEU.23", "DEU.24"], title: "Exclusion from Assembly" },
  { day: 86, readings: ["DEU.25", "DEU.26"], title: "Firstfruits and Tithes" },
  { day: 87, readings: ["DEU.27", "DEU.28"], title: "Blessings and Curses" },
  { day: 88, readings: ["DEU.29", "DEU.30"], title: "Covenant Renewed" },
  { day: 89, readings: ["DEU.31", "DEU.32"], title: "Moses' Song" },
  { day: 90, readings: ["DEU.33", "DEU.34"], title: "Moses' Death" },
  { day: 91, readings: ["JOS.1", "JOS.2"], title: "Rahab and the Spies" },
  { day: 92, readings: ["JOS.3", "JOS.4"], title: "Crossing the Jordan" },
  { day: 93, readings: ["JOS.5", "JOS.6"], title: "Fall of Jericho" },
  { day: 94, readings: ["JOS.7", "JOS.8"], title: "Achan's Sin" },
  { day: 95, readings: ["JOS.9", "JOS.10"], title: "Sun Stands Still" },
  { day: 96, readings: ["JOS.11", "JOS.12"], title: "Northern Campaign" },
  { day: 97, readings: ["JOS.13", "JOS.14"], title: "Dividing the Land" },
  { day: 98, readings: ["JOS.15", "JOS.16", "JOS.17"], title: "Tribal Allotments" },
  { day: 99, readings: ["JOS.18", "JOS.19"], title: "More Allotments" },
  { day: 100, readings: ["JOS.20", "JOS.21"], title: "Cities of Refuge" },
  { day: 101, readings: ["JOS.22", "JOS.23", "JOS.24"], title: "Joshua's Farewell" },
  { day: 102, readings: ["JDG.1", "JDG.2"], title: "Israel Disobeys" },
  { day: 103, readings: ["JDG.3", "JDG.4"], title: "Deborah and Barak" },
  { day: 104, readings: ["JDG.5", "JDG.6"], title: "Gideon Called" },
  { day: 105, readings: ["JDG.7", "JDG.8"], title: "Gideon's Victory" },
  { day: 106, readings: ["JDG.9"], title: "Abimelech's Reign" },
  { day: 107, readings: ["JDG.10", "JDG.11"], title: "Jephthah" },
  { day: 108, readings: ["JDG.12", "JDG.13"], title: "Samson's Birth" },
  { day: 109, readings: ["JDG.14", "JDG.15"], title: "Samson's Strength" },
  { day: 110, readings: ["JDG.16"], title: "Samson and Delilah" },
  { day: 111, readings: ["JDG.17", "JDG.18"], title: "Micah's Idols" },
  { day: 112, readings: ["JDG.19", "JDG.20"], title: "Civil War" },
  { day: 113, readings: ["JDG.21", "RUT.1"], title: "Ruth and Naomi" },
  { day: 114, readings: ["RUT.2", "RUT.3", "RUT.4"], title: "Ruth and Boaz" },
  { day: 115, readings: ["1SA.1", "1SA.2"], title: "Samuel's Birth" },
  { day: 116, readings: ["1SA.3", "1SA.4"], title: "The Lord Calls Samuel" },
  { day: 117, readings: ["1SA.5", "1SA.6"], title: "The Ark Captured" },
  { day: 118, readings: ["1SA.7", "1SA.8"], title: "Israel Asks for a King" },
  { day: 119, readings: ["1SA.9", "1SA.10"], title: "Saul Anointed King" },
  { day: 120, readings: ["1SA.11", "1SA.12"], title: "Saul Confirmed as King" },
  { day: 121, readings: ["1SA.13", "1SA.14"], title: "Saul's Disobedience" },
  { day: 122, readings: ["1SA.15"], title: "Saul Rejected as King" },
  { day: 123, readings: ["1SA.16"], title: "David Anointed" },
  { day: 124, readings: ["1SA.17"], title: "David and Goliath" },
  { day: 125, readings: ["1SA.18", "1SA.19"], title: "Saul's Jealousy" },
  { day: 126, readings: ["1SA.20"], title: "David and Jonathan" },
  { day: 127, readings: ["1SA.21", "1SA.22"], title: "David Flees from Saul" },
  { day: 128, readings: ["1SA.23", "1SA.24"], title: "David Spares Saul" },
  { day: 129, readings: ["1SA.25"], title: "David and Abigail" },
  { day: 130, readings: ["1SA.26", "1SA.27"], title: "David Spares Saul Again" },
  { day: 131, readings: ["1SA.28", "1SA.29", "1SA.30"], title: "Witch of Endor" },
  { day: 132, readings: ["1SA.31", "2SA.1"], title: "Death of Saul" },
  { day: 133, readings: ["2SA.2", "2SA.3"], title: "David King of Judah" },
  { day: 134, readings: ["2SA.4", "2SA.5"], title: "David King of Israel" },
  { day: 135, readings: ["2SA.6", "2SA.7"], title: "God's Covenant with David" },
  { day: 136, readings: ["2SA.8", "2SA.9", "2SA.10"], title: "David's Victories" },
  { day: 137, readings: ["2SA.11", "2SA.12"], title: "David and Bathsheba" },
  { day: 138, readings: ["2SA.13", "2SA.14"], title: "Amnon and Tamar" },
  { day: 139, readings: ["2SA.15", "2SA.16"], title: "Absalom's Conspiracy" },
  { day: 140, readings: ["2SA.17", "2SA.18"], title: "Absalom's Death" },
  { day: 141, readings: ["2SA.19", "2SA.20"], title: "David Returns" },
  { day: 142, readings: ["2SA.21", "2SA.22"], title: "David's Song of Praise" },
  { day: 143, readings: ["2SA.23", "2SA.24"], title: "David's Last Words" },
  { day: 144, readings: ["1KI.1", "1KI.2"], title: "Solomon Becomes King" },
  { day: 145, readings: ["1KI.3", "1KI.4"], title: "Solomon's Wisdom" },
  { day: 146, readings: ["1KI.5", "1KI.6"], title: "Building the Temple" },
  { day: 147, readings: ["1KI.7"], title: "Solomon's Palace" },
  { day: 148, readings: ["1KI.8"], title: "Temple Dedication" },
  { day: 149, readings: ["1KI.9", "1KI.10"], title: "Queen of Sheba" },
  { day: 150, readings: ["1KI.11"], title: "Solomon's Wives" },
  { day: 151, readings: ["1KI.12"], title: "Kingdom Divided" },
  { day: 152, readings: ["1KI.13", "1KI.14"], title: "Prophets and Kings" },
  { day: 153, readings: ["1KI.15", "1KI.16"], title: "Kings of Israel and Judah" },
  { day: 154, readings: ["1KI.17"], title: "Elijah Fed by Ravens" },
  { day: 155, readings: ["1KI.18"], title: "Elijah on Mount Carmel" },
  { day: 156, readings: ["1KI.19"], title: "Elijah and the Still Small Voice" },
  { day: 157, readings: ["1KI.20", "1KI.21"], title: "Ahab and Naboth's Vineyard" },
  { day: 158, readings: ["1KI.22", "2KI.1"], title: "Ahab's Death" },
  { day: 159, readings: ["2KI.2"], title: "Elijah Taken to Heaven" },
  { day: 160, readings: ["2KI.3", "2KI.4"], title: "Elisha's Miracles" },
  { day: 161, readings: ["2KI.5"], title: "Naaman Healed" },
  { day: 162, readings: ["2KI.6", "2KI.7"], title: "Siege of Samaria" },
  { day: 163, readings: ["2KI.8", "2KI.9"], title: "Jehu Anointed King" },
  { day: 164, readings: ["2KI.10", "2KI.11"], title: "Athaliah and Joash" },
  { day: 165, readings: ["2KI.12", "2KI.13"], title: "Joash Repairs the Temple" },
  { day: 166, readings: ["2KI.14", "2KI.15"], title: "Kings of Israel and Judah" },
  { day: 167, readings: ["2KI.16", "2KI.17"], title: "Fall of Samaria" },
  { day: 168, readings: ["2KI.18", "2KI.19"], title: "Hezekiah's Reign" },
  { day: 169, readings: ["2KI.20", "2KI.21"], title: "Hezekiah's Illness" },
  { day: 170, readings: ["2KI.22", "2KI.23"], title: "Josiah's Reforms" },
  { day: 171, readings: ["2KI.24", "2KI.25"], title: "Fall of Jerusalem" },
  { day: 172, readings: ["MAT.1", "MAT.2"], title: "Birth of Jesus" },
  { day: 173, readings: ["MAT.3", "MAT.4"], title: "Jesus' Baptism and Temptation" },
  { day: 174, readings: ["MAT.5"], title: "Sermon on the Mount" },
  { day: 175, readings: ["MAT.6"], title: "Lord's Prayer" },
  { day: 176, readings: ["MAT.7", "MAT.8"], title: "Jesus' Authority" },
  { day: 177, readings: ["MAT.9", "MAT.10"], title: "Twelve Disciples" },
  { day: 178, readings: ["MAT.11", "MAT.12"], title: "John the Baptist" },
  { day: 179, readings: ["MAT.13"], title: "Parables of the Kingdom" },
  { day: 180, readings: ["MAT.14", "MAT.15"], title: "Feeding the Five Thousand" },
  { day: 181, readings: ["MAT.16", "MAT.17"], title: "Peter's Confession" },
  { day: 182, readings: ["MAT.18"], title: "Greatest in the Kingdom" },
  { day: 183, readings: ["MAT.19", "MAT.20"], title: "Rich Young Ruler" },
  { day: 184, readings: ["MAT.21"], title: "Triumphal Entry" },
  { day: 185, readings: ["MAT.22", "MAT.23"], title: "Woes to Pharisees" },
  { day: 186, readings: ["MAT.24"], title: "Signs of the End" },
  { day: 187, readings: ["MAT.25"], title: "Parable of the Talents" },
  { day: 188, readings: ["MAT.26"], title: "Last Supper" },
  { day: 189, readings: ["MAT.27"], title: "Crucifixion" },
  { day: 190, readings: ["MAT.28", "MRK.1"], title: "Resurrection and New Beginning" },
  { day: 191, readings: ["MRK.2", "MRK.3"], title: "Jesus Calls Disciples" },
  { day: 192, readings: ["MRK.4", "MRK.5"], title: "Parables and Miracles" },
  { day: 193, readings: ["MRK.6", "MRK.7"], title: "Jesus Feeds Multitudes" },
  { day: 194, readings: ["MRK.8", "MRK.9"], title: "Transfiguration" },
  { day: 195, readings: ["MRK.10"], title: "Jesus and the Children" },
  { day: 196, readings: ["MRK.11", "MRK.12"], title: "Authority Questioned" },
  { day: 197, readings: ["MRK.13"], title: "End Times Teaching" },
  { day: 198, readings: ["MRK.14"], title: "Betrayal and Arrest" },
  { day: 199, readings: ["MRK.15", "MRK.16"], title: "Death and Resurrection" },
  { day: 200, readings: ["LUK.1"], title: "Birth Announcements" },
  { day: 201, readings: ["LUK.2"], title: "Birth of Jesus" },
  { day: 202, readings: ["LUK.3", "LUK.4"], title: "Ministry Begins" },
  { day: 203, readings: ["LUK.5", "LUK.6"], title: "Calling the Twelve" },
  { day: 204, readings: ["LUK.7", "LUK.8"], title: "Parables and Miracles" },
  { day: 205, readings: ["LUK.9"], title: "Transfiguration" },
  { day: 206, readings: ["LUK.10"], title: "Good Samaritan" },
  { day: 207, readings: ["LUK.11", "LUK.12"], title: "Teaching on Prayer" },
  { day: 208, readings: ["LUK.13", "LUK.14"], title: "Parables of the Kingdom" },
  { day: 209, readings: ["LUK.15"], title: "Parables of the Lost" },
  { day: 210, readings: ["LUK.16", "LUK.17"], title: "Rich Man and Lazarus" },
  { day: 211, readings: ["LUK.18", "LUK.19"], title: "Zacchaeus" },
  { day: 212, readings: ["LUK.20", "LUK.21"], title: "End Times" },
  { day: 213, readings: ["LUK.22"], title: "Last Supper" },
  { day: 214, readings: ["LUK.23"], title: "Crucifixion" },
  { day: 215, readings: ["LUK.24", "JHN.1"], title: "Resurrection and the Word" },
  { day: 216, readings: ["JHN.2", "JHN.3"], title: "Born Again" },
  { day: 217, readings: ["JHN.4", "JHN.5"], title: "Woman at the Well" },
  { day: 218, readings: ["JHN.6"], title: "Bread of Life" },
  { day: 219, readings: ["JHN.7", "JHN.8"], title: "Living Water" },
  { day: 220, readings: ["JHN.9", "JHN.10"], title: "Good Shepherd" },
  { day: 221, readings: ["JHN.11"], title: "Lazarus Raised" },
  { day: 222, readings: ["JHN.12", "JHN.13"], title: "Washing Feet" },
  { day: 223, readings: ["JHN.14", "JHN.15"], title: "I Am the Way" },
  { day: 224, readings: ["JHN.16", "JHN.17"], title: "High Priestly Prayer" },
  { day: 225, readings: ["JHN.18"], title: "Arrest and Trial" },
  { day: 226, readings: ["JHN.19"], title: "Crucifixion" },
  { day: 227, readings: ["JHN.20", "JHN.21"], title: "Resurrection Appearances" },
  { day: 228, readings: ["ACT.1", "ACT.2"], title: "Pentecost" },
  { day: 229, readings: ["ACT.3", "ACT.4"], title: "Peter Heals and Preaches" },
  { day: 230, readings: ["ACT.5", "ACT.6"], title: "Ananias and Sapphira" },
  { day: 231, readings: ["ACT.7"], title: "Stephen's Speech" },
  { day: 232, readings: ["ACT.8", "ACT.9"], title: "Saul's Conversion" },
  { day: 233, readings: ["ACT.10", "ACT.11"], title: "Peter and Cornelius" },
  { day: 234, readings: ["ACT.12", "ACT.13"], title: "First Missionary Journey" },
  { day: 235, readings: ["ACT.14", "ACT.15"], title: "Jerusalem Council" },
  { day: 236, readings: ["ACT.16", "ACT.17"], title: "Paul in Athens" },
  { day: 237, readings: ["ACT.18", "ACT.19"], title: "Paul in Ephesus" },
  { day: 238, readings: ["ACT.20", "ACT.21"], title: "Paul's Farewell" },
  { day: 239, readings: ["ACT.22", "ACT.23"], title: "Paul's Defense" },
  { day: 240, readings: ["ACT.24", "ACT.25", "ACT.26"], title: "Paul Before Felix and Agrippa" },
  { day: 241, readings: ["ACT.27", "ACT.28"], title: "Shipwreck and Rome" },
  { day: 242, readings: ["ROM.1", "ROM.2"], title: "God's Righteousness Revealed" },
  { day: 243, readings: ["ROM.3", "ROM.4"], title: "Justified by Faith" },
  { day: 244, readings: ["ROM.5", "ROM.6"], title: "Peace with God" },
  { day: 245, readings: ["ROM.7", "ROM.8"], title: "Life in the Spirit" },
  { day: 246, readings: ["ROM.9", "ROM.10"], title: "God's Sovereignty" },
  { day: 247, readings: ["ROM.11", "ROM.12"], title: "Living Sacrifice" },
  { day: 248, readings: ["ROM.13", "ROM.14", "ROM.15"], title: "Love and Unity" },
  { day: 249, readings: ["ROM.16", "1CO.1"], title: "Greetings and Divisions" },
  { day: 250, readings: ["1CO.2", "1CO.3", "1CO.4"], title: "Wisdom of God" },
  { day: 251, readings: ["1CO.5", "1CO.6"], title: "Immorality Judged" },
  { day: 252, readings: ["1CO.7"], title: "Marriage" },
  { day: 253, readings: ["1CO.8", "1CO.9", "1CO.10"], title: "Food Sacrificed to Idols" },
  { day: 254, readings: ["1CO.11", "1CO.12"], title: "Spiritual Gifts" },
  { day: 255, readings: ["1CO.13", "1CO.14"], title: "Love is Greatest" },
  { day: 256, readings: ["1CO.15", "1CO.16"], title: "Resurrection" },
  { day: 257, readings: ["2CO.1", "2CO.2", "2CO.3"], title: "Comfort in Affliction" },
  { day: 258, readings: ["2CO.4", "2CO.5"], title: "Treasure in Jars of Clay" },
  { day: 259, readings: ["2CO.6", "2CO.7"], title: "Paul's Joy" },
  { day: 260, readings: ["2CO.8", "2CO.9"], title: "Generosity Encouraged" },
  { day: 261, readings: ["2CO.10", "2CO.11"], title: "Paul's Defense" },
  { day: 262, readings: ["2CO.12", "2CO.13"], title: "Paul's Thorn" },
  { day: 263, readings: ["GAL.1", "GAL.2", "GAL.3"], title: "Faith not Works" },
  { day: 264, readings: ["GAL.4", "GAL.5", "GAL.6"], title: "Freedom in Christ" },
  { day: 265, readings: ["EPH.1", "EPH.2", "EPH.3"], title: "Saved by Grace" },
  { day: 266, readings: ["EPH.4", "EPH.5", "EPH.6"], title: "Armor of God" },
  { day: 267, readings: ["PHP.1", "PHP.2"], title: "Joy in Christ" },
  { day: 268, readings: ["PHP.3", "PHP.4"], title: "Rejoice Always" },
  { day: 269, readings: ["COL.1", "COL.2"], title: "Christ is Supreme" },
  { day: 270, readings: ["COL.3", "COL.4"], title: "New Life in Christ" },
  { day: 271, readings: ["1TH.1", "1TH.2", "1TH.3"], title: "Thessalonians' Faith" },
  { day: 272, readings: ["1TH.4", "1TH.5", "2TH.1"], title: "The Coming of the Lord" },
  { day: 273, readings: ["2TH.2", "2TH.3"], title: "Stand Firm" },
  { day: 274, readings: ["1TI.1", "1TI.2", "1TI.3"], title: "Instructions for the Church" },
  { day: 275, readings: ["1TI.4", "1TI.5", "1TI.6"], title: "Godliness with Contentment" },
  { day: 276, readings: ["2TI.1", "2TI.2"], title: "Be Strong in Grace" },
  { day: 277, readings: ["2TI.3", "2TI.4"], title: "All Scripture is God-Breathed" },
  { day: 278, readings: ["TIT.1", "TIT.2", "TIT.3"], title: "Sound Doctrine" },
  { day: 279, readings: ["PHM.1", "HEB.1", "HEB.2"], title: "Jesus Superior to Angels" },
  { day: 280, readings: ["HEB.3", "HEB.4"], title: "Jesus Greater Than Moses" },
  { day: 281, readings: ["HEB.5", "HEB.6", "HEB.7"], title: "Melchizedek Priesthood" },
  { day: 282, readings: ["HEB.8", "HEB.9"], title: "New Covenant" },
  { day: 283, readings: ["HEB.10"], title: "Draw Near with Confidence" },
  { day: 284, readings: ["HEB.11"], title: "Faith Hall of Fame" },
  { day: 285, readings: ["HEB.12", "HEB.13"], title: "Run with Endurance" },
  { day: 286, readings: ["JAS.1", "JAS.2"], title: "Faith and Deeds" },
  { day: 287, readings: ["JAS.3", "JAS.4", "JAS.5"], title: "Taming the Tongue" },
  { day: 288, readings: ["1PE.1", "1PE.2"], title: "Living Hope" },
  { day: 289, readings: ["1PE.3", "1PE.4", "1PE.5"], title: "Suffering for Good" },
  { day: 290, readings: ["2PE.1", "2PE.2", "2PE.3"], title: "False Teachers" },
  { day: 291, readings: ["1JN.1", "1JN.2"], title: "Walk in the Light" },
  { day: 292, readings: ["1JN.3", "1JN.4"], title: "God is Love" },
  { day: 293, readings: ["1JN.5", "2JN.1", "3JN.1", "JUD.1"], title: "Overcome the World" },
  { day: 294, readings: ["REV.1", "REV.2"], title: "Letters to the Churches" },
  { day: 295, readings: ["REV.3", "REV.4"], title: "Throne Room of Heaven" },
  { day: 296, readings: ["REV.5", "REV.6"], title: "The Lamb and the Seals" },
  { day: 297, readings: ["REV.7", "REV.8", "REV.9"], title: "The Trumpets" },
  { day: 298, readings: ["REV.10", "REV.11"], title: "The Two Witnesses" },
  { day: 299, readings: ["REV.12", "REV.13"], title: "The Dragon and the Beasts" },
  { day: 300, readings: ["REV.14", "REV.15", "REV.16"], title: "The Bowls of Wrath" },
  { day: 301, readings: ["REV.17", "REV.18"], title: "Fall of Babylon" },
  { day: 302, readings: ["REV.19", "REV.20"], title: "Final Judgment" },
  { day: 303, readings: ["REV.21", "REV.22"], title: "New Heaven and New Earth" },
  { day: 304, readings: ["PSA.1", "PSA.2", "PSA.3"], title: "Psalms of Trust" },
  { day: 305, readings: ["PSA.4", "PSA.5", "PSA.6", "PSA.7"], title: "Prayers for Help" },
  { day: 306, readings: ["PSA.8", "PSA.9", "PSA.10"], title: "God's Glory and Justice" },
  { day: 307, readings: ["PSA.11", "PSA.12", "PSA.13", "PSA.14"], title: "Trust in the Lord" },
  { day: 308, readings: ["PSA.15", "PSA.16", "PSA.17"], title: "Dwelling with God" },
  { day: 309, readings: ["PSA.18"], title: "Song of Deliverance" },
  { day: 310, readings: ["PSA.19", "PSA.20", "PSA.21"], title: "God's Glory Declared" },
  { day: 311, readings: ["PSA.22", "PSA.23"], title: "The Good Shepherd" },
  { day: 312, readings: ["PSA.24", "PSA.25", "PSA.26"], title: "The King of Glory" },
  { day: 313, readings: ["PSA.27", "PSA.28", "PSA.29"], title: "The Lord is My Light" },
  { day: 314, readings: ["PSA.30", "PSA.31"], title: "Joy Comes in the Morning" },
  { day: 315, readings: ["PSA.32", "PSA.33"], title: "Blessed is the Forgiven" },
  { day: 316, readings: ["PSA.34", "PSA.35"], title: "Taste and See" },
  { day: 317, readings: ["PSA.36", "PSA.37"], title: "Trust and Wait" },
  { day: 318, readings: ["PSA.38", "PSA.39", "PSA.40"], title: "Hope in God" },
  { day: 319, readings: ["PSA.41", "PSA.42", "PSA.43"], title: "Thirst for God" },
  { day: 320, readings: ["PSA.44", "PSA.45", "PSA.46"], title: "God is Our Refuge" },
  { day: 321, readings: ["PSA.47", "PSA.48", "PSA.49"], title: "God Reigns" },
  { day: 322, readings: ["PSA.50", "PSA.51"], title: "Create in Me a Clean Heart" },
  { day: 323, readings: ["PSA.52", "PSA.53", "PSA.54"], title: "Trusting God" },
  { day: 324, readings: ["PSA.55", "PSA.56", "PSA.57"], title: "Cast Your Burden" },
  { day: 325, readings: ["PSA.58", "PSA.59", "PSA.60"], title: "Prayers for Justice" },
  { day: 326, readings: ["PSA.61", "PSA.62", "PSA.63"], title: "My Soul Thirsts" },
  { day: 327, readings: ["PSA.64", "PSA.65", "PSA.66"], title: "Shouts of Joy" },
  { day: 328, readings: ["PSA.67", "PSA.68"], title: "Let the Nations Praise" },
  { day: 329, readings: ["PSA.69"], title: "Save Me, O God" },
  { day: 330, readings: ["PSA.70", "PSA.71", "PSA.72"], title: "From Youth to Old Age" },
  { day: 331, readings: ["PSA.73", "PSA.74"], title: "God is Good" },
  { day: 332, readings: ["PSA.75", "PSA.76", "PSA.77"], title: "I Will Remember" },
  { day: 333, readings: ["PSA.78"], title: "Lessons from History" },
  { day: 334, readings: ["PSA.79", "PSA.80"], title: "Restore Us, O God" },
  { day: 335, readings: ["PSA.81", "PSA.82", "PSA.83"], title: "Sing for Joy" },
  { day: 336, readings: ["PSA.84", "PSA.85"], title: "Better is One Day" },
  { day: 337, readings: ["PSA.86", "PSA.87", "PSA.88"], title: "Teach Me Your Way" },
  { day: 338, readings: ["PSA.89"], title: "God's Faithfulness" },
  { day: 339, readings: ["PSA.90", "PSA.91"], title: "Under His Wings" },
  { day: 340, readings: ["PSA.92", "PSA.93", "PSA.94"], title: "The Lord Reigns" },
  { day: 341, readings: ["PSA.95", "PSA.96", "PSA.97"], title: "Worship the Lord" },
  { day: 342, readings: ["PSA.98", "PSA.99", "PSA.100"], title: "Shout for Joy" },
  { day: 343, readings: ["PSA.101", "PSA.102", "PSA.103"], title: "Bless the Lord" },
  { day: 344, readings: ["PSA.104"], title: "God's Creation" },
  { day: 345, readings: ["PSA.105"], title: "Remember His Wonders" },
  { day: 346, readings: ["PSA.106"], title: "Confession and Praise" },
  { day: 347, readings: ["PSA.107"], title: "Give Thanks to the Lord" },
  { day: 348, readings: ["PSA.108", "PSA.109", "PSA.110"], title: "At Your Right Hand" },
  { day: 349, readings: ["PSA.111", "PSA.112", "PSA.113"], title: "Praise the Lord" },
  { day: 350, readings: ["PSA.114", "PSA.115", "PSA.116"], title: "I Love the Lord" },
  { day: 351, readings: ["PSA.117", "PSA.118"], title: "Give Thanks" },
  { day: 352, readings: ["PSA.119.1-88"], title: "Your Word is a Lamp" },
  { day: 353, readings: ["PSA.119.89-176"], title: "I Delight in Your Law" },
  { day: 354, readings: ["PSA.120", "PSA.121", "PSA.122", "PSA.123"], title: "Songs of Ascent 1" },
  { day: 355, readings: ["PSA.124", "PSA.125", "PSA.126", "PSA.127"], title: "Songs of Ascent 2" },
  { day: 356, readings: ["PSA.128", "PSA.129", "PSA.130", "PSA.131"], title: "Songs of Ascent 3" },
  { day: 357, readings: ["PSA.132", "PSA.133", "PSA.134"], title: "Songs of Ascent 4" },
  { day: 358, readings: ["PSA.135", "PSA.136"], title: "His Love Endures Forever" },
  { day: 359, readings: ["PSA.137", "PSA.138", "PSA.139"], title: "Wonderfully Made" },
  { day: 360, readings: ["PSA.140", "PSA.141", "PSA.142", "PSA.143"], title: "Deliver Me" },
  { day: 361, readings: ["PSA.144", "PSA.145"], title: "Great is the Lord" },
  { day: 362, readings: ["PSA.146", "PSA.147"], title: "Praise the Lord" },
  { day: 363, readings: ["PSA.148", "PSA.149", "PSA.150"], title: "Let Everything Praise" },
  { day: 364, readings: ["PRO.1", "PRO.2", "PRO.3"], title: "The Fear of the Lord" },
  { day: 365, readings: ["PRO.4", "PRO.5", "PRO.6", "PRO.7"], title: "Wisdom's Call" },
];

async function seedBibleIn1Year() {
  try {
    console.log("🌱 Starting Bible in 1 Year seed...");

    const plan = await storage.createReadingPlan({
      name: "Bible in 1 Year",
      description: "Read through the entire Bible in one year with a carefully structured plan covering both Old and New Testament books systematically.",
      totalDays: 365,
      language: 'en',
      isActive: true,
    });

    console.log(`✅ Created reading plan: ${plan.name} (${plan.id})`);

    for (const dayData of bibleIn1YearPlan) {
      await storage.createReadingPlanDay({
        planId: plan.id,
        dayNumber: dayData.day,
        readings: dayData.readings,
        title: dayData.title,
      });
    }

    console.log(`✅ Seeded ${bibleIn1YearPlan.length} days of Bible in 1 Year reading plan`);
    console.log("✨ Bible in 1 Year seed complete!");
  } catch (error) {
    console.error("❌ Error seeding Bible in 1 Year:", error);
    throw error;
  }
}

seedBibleIn1Year();
